name: ETL workflow for Group 1

on:
#  schedule:
#    - cron: '0 */3 * * *' # Run every 3 hours
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION', '**/*.R', '**/*.qmd') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("dplyr","readr","RSQLite","lubridate","rmarkdown","DBI"))'

      - name: Install Quarto
        run: |
          QUARTO_URL=$(curl -s https://api.github.com/repos/quarto-dev/quarto-cli/releases/latest \
                 | grep "browser_download_url.*quarto-linux-amd64.deb" \
                 | grep -o "https://[^ \"]*")
          if [[ -z "$QUARTO_URL" ]]; then
          echo "Failed to find the Quarto download URL"
          exit 1
          fi
          curl -L -o quarto-linux-amd64.deb "$QUARTO_URL"
          if [ $? -ne 0 ]; then
          echo "Failed to download Quarto"
          exit 1
          fi
          sudo dpkg -i quarto-linux-amd64.deb

      - name: Render .qmd file
        run: |
          quarto render R/data_pipeline_render.qmd

      - name: Add files
        run: |
          git config --global user.email "vignesh.parthasarathy@warwick.ac.uk"
          git config --global user.name "Vickyyyy98"
          git add ../database/ecommerce_databse.db
          git add R/data_pipeline_render.pdf

      - name: Commit files
        run: |
          git commit -m "Mock Data Upload" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
